language: ruby
rvm:
- 2.1.1
addons:
  code_climate:
    repo_token:
      secure: gG/jCFKIUxaSEMkJCShfL2rMzUpA7drnEPTuAGBiOGQ+ZREkAZoFUby29IqRbNGE6U9WwarcuYERU4DhZffFAT9Vvereoo/9F7YVB8HLJAixc5s8Z+Ulg/RgGieT0hA1ZtvQo1k/osI0F48bTL3rZfFPOJTpAFduFF0xy/NTvvc=
