language: ruby

rvm:
  - 2.1.1

addons:
  code_climate:
    repo_token:
      secure: pC6nMKkuv0aS00grV3wE4Ex7RTxRSoFX7fiU0KSLOUJeVfVuY9hTBXheeyO56d1gkfNauXpc0y4MlqpbUuI4gPdYUp2beNBpifRyIvEe9Ul3wDEDsBVyFp2ATw4TBMjESW0oXGBWAYuglpjIYAupZh+GpkMxbd8+9lE1gKLMvBw=